### ISSUE TITLE
"Error: Table Header is too long" multiple tables on multiple pages

### ISSUE THREAD

**Issue by hirviid** [rkusa/pdfjs#213] opened 2020-05-20 15:54 UTC
Hello

When I want to render multiple tables, with every table its own header and the tables exceed 1 page I get this error:

```
"Error: Table Header is to long (tried to execute a page break inside the header)",
            "    at TableHeader._pageBreak (/path/to/node_modules/pdfjs/lib/tableheader.js:27:11)",
            "    at Cell._pageBreak (/path/to/node_modules/pdfjs/lib/cell.js:61:26)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

Am I doing something wrong? Is there a workaround?

Thanks!

**Comment by rkusa** [comment] 2020-05-22 12:41
Hi,

this error should only happen if the table header itself exceeds one page, but it shouldn't happen if the following table body exceeds a page.

Could you reduce your code to a minimal example I could use to check the error?

Thanks

**Comment by hirviid** [comment] 2020-06-05 08:39
Hi 

I made an example: https://github.com/hirviid/pdfjs-issue-213

See table.header in line 80 and 86 in index.js.

It looks like the error only occurs when I use 2 table headers directly beneath each other. If I change one of them to a table.row, it renders correctly. I thought that I had the problem with one header as well, but I don't have that example anymore.

**Comment by rkusa** [comment] 2020-06-09 08:08
Thanks a lot for the example! Multiple table headers are indeed not intended. I've added an error when multiple headers are added to a table. Adding one header with multiple rows should be used instead. 👍

**Comment by jrogelstad** [comment] 2021-08-07 12:28
Hi Markus,

This is a really nice framework! Very powerful. Thank you for publishing it. I've also run into the "header too long" error. If the content preceding a table is such that the header has the misfortune of landing on the very end of a page, then you get this error.

I was able to reproduce it in your playground by modifying a bit of your code to add repeating cells like this:

let x = 0;
let max = 20;
while (x < max) {
    doc.cell({ paddingBottom: 0.5*pdf.cm }).text()
      .add('For more information visit the')
      .add('Documentation', {
        link: 'https://github.com/rkusa/pdfjs/tree/master/docs',
        underline: true,
        color: 0x569cd6
      })
    x += 1;
}

As long as "max" is less than 20 everything's fine. Once you get to 20 the error is thrown. My application is data driven so there's no way to predict or control when it might happen, but I've seen it happen frequently enough that the only recourse I can see is to simply make the header a regular row, which prevents the error, but means I don't get the nice feature of the header repeating on new pages.

I've hacked around your code off and on for a couple days now, but have not figured out a way to prevent the error while still preserving the repeating headers. I would love to hear if there is either a work around or resolution to this. Thanks in advance.

Best Regards,

John

**Comment by rkusa** [comment] 2021-08-18 08:47
@jrogelstad thanks for the report. If I understand your example correctly, your header is indeed just getting too long so that it wouldn't fit on a single page. A header that doesn't fit on a page doesn't really make a lot of sense to me I have to admit. What would - in an ideal world - `pdfjs`'s behaviour in this case be in your opinion so that it works well with your data-driven use-case?

**Comment by jrogelstad** [comment] 2021-08-18 12:25
Here's an example so you can se the use case:
https://drive.google.com/file/d/17DlelD2KXH2Vkem3ju9qpKtWhucNFouZ/view?usp=sharing

What's going on is there's a variable number of tables that can be printed with each table being of variable length. In the example shown the labels and fields at the top are a table, with subsequent tables below it.  The 3rd table is what lands at the bottom of the page and throws an error if I try to use table headers. The error doesn't happen if the comments are blank in this example because the 2nd table ends higher up, but then if there's another row or two in the 2nd table, the same problem can happen.

Ideally what we'd want is if a table header gets caught at the bottom of a page with insufficient room to render, it is nudged to the following page, the same as happens in the example when I just handle the header as a regular row.

**Comment by rkusa** [comment] 2021-11-08 08:48
Ah gotcha, I now understand the issue. I previously didn't understand that it was about table headers that are not actually taller than a page, they are just rendered at the bottom of the page. This is definitely a bug, and the header should be moved to the next page instead.

**Comment by jrogelstad** [comment] 2021-11-09 02:24
Exactly! Thanks for looking into it.
    	Get Outlook for iOS
    
  

 From: Markus Ast ***@***.***>Sent: Monday, November 8, 2021 3:48 AMTo: rkusa/pdfjsCc: John Rogelstad; MentionSubject: Re: [rkusa/pdfjs] "Error: Table Header is too long" multiple tables on multiple pages (#213) 
Ah gotcha, I now understand the issue. I previously didn't understand that it was about table headers that are not actually taller than a page, they are just rendered at the bottom of the page. This is definitely a bug, and the header should be moved to the next page instead.

**Comment by rkusa** [comment] 2021-11-09 08:57
Should be fixed, I'll release a new version later today

**Closed** 2021-11-09 08:56 UTC

**Comment by jrogelstad** [comment] 2021-11-13 19:21
Excellent! Seems to work fine. Thanks again for your help, Markus.
