### ISSUE TITLE
OTF fonts don't show up on printed page

### ISSUE THREAD

**Issue by RGBz** [rkusa/pdfjs#83] opened 2018-03-22 17:16 UTC
Even when the generated PDF looks good on the computer, if you try and print any OTF fonts to paper they don't show up in the print out. See below for details:
```js
const fs = require('fs');
const pdf = require('pdfjs');
const helvetica = new pdf.Font(require('pdfjs/font/helvetica.json'));
const openSans = new pdf.Font(fs.readFileSync('node_modules/pdfjs/test/fixtures/font/opensans/bold.ttf'));

const doc = new pdf.Document({ font: helvetica, padding: 10 });
doc.pipe(fs.createWriteStream('output.pdf'));

// This prints "hello good bye"
doc.text().add('hello good bye');

// This prints "              "
doc.text().add('hello good bye', { font: openSans });

// This prints "hello good bye"
doc.text().add('hello').add('good bye');

// This prints "              "
doc.text().add('hello', { font: openSans }).add('good bye', { font: openSans });

// This prints "hello         "
doc.text().add('hello').add('good bye', { font: openSans });

// This prints "      good bye"
doc.text().add('hello', { font: openSans }).add('good bye');

doc.end();
```

**Comment by RGBz** [comment] 2018-03-22 18:08
This works when printed from Adobe Reader, but not Mac Preview.

**Comment by rkusa** [comment] 2018-03-22 18:09
What a bug - found some applications that print empty pages as reported but also applications that print correctly 😱

So much for PDFs are WYSIWYG. Definitely something that needs to be fixed (also for my own use of the library). Thanks for reporting!

**Comment by rkusa** [comment] 2018-03-23 10:57
It seems to be fixed on master. But I am not to comfortable with this change yet to already release a new version to NPM. I have to do some more PDF reference reading and might have to bump the PDF version of the resulting documents to `1.6`.

**Comment by RGBz** [comment] 2018-03-23 15:53
Interesting, I can try it out and see if what's in master works for printing from the PDF viewers I have. What are the tradeoffs of going to 1.6?

**Comment by rkusa** [comment] 2018-03-24 07:44
I've tested Acrobat Reader, Preview and PDF Expert and it works for all of them now. If you have others, yes, it would be nice if you could test them. (I think the issue is with all apps that use the native macOS print dialog) I still have to test on Linux and Windows.

I am eventually aiming at getting PDF/A-3 compliant PDFs. I falsely remembered that they are based on PDF 1.5, but this is wrong, they are based on PDF 1.7. So I am personally fine with setting the PDF version with 1.6 / 1.7.

**Comment by rkusa** [comment] 2018-03-26 05:47
I have set the PDF version to 1.6 for now. I'll will publish a new NPM version later today. Thanks again for reporting this issue!

**Closed by rkusa** 2018-03-26 05:47 UTC
